language: node_js
node_js:
  - "6"
before_deploy: yarn build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  repo: easylist-thailand/easylist-thailand.github.io
  local_dir: ./build
  target_branch: master
  on:
    branch: master
