language: node_js
node_js:
  - "lts/*"
branches:
  only:
    - master
before_deploy: npm run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  repo: easylist-thailand/easylist-thailand.github.io
  local_dir: ./dist
  target_branch: master
  on:
    branch: master
